// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// K8sSvc is an autogenerated mock type for the K8sSvc type
type K8sSvc struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *K8sSvc) Client() client.Client {
	ret := _m.Called()

	var r0 client.Client
	if rf, ok := ret.Get(0).(func() client.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	return r0
}
