// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserSvc is an autogenerated mock type for the UserSvc type
type UserSvc struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userName, password
func (_m *UserSvc) Create(ctx context.Context, userName string, password string) error {
	ret := _m.Called(ctx, userName, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userName, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: ctx, userName, password
func (_m *UserSvc) Login(ctx context.Context, userName string, password string) (string, error) {
	ret := _m.Called(ctx, userName, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userName, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userName, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
