# permissions for end users to view useraccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: useraccount-viewer-role
rules:
- apiGroups:
  - cloud.kubexcloud.com
  resources:
  - useraccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.kubexcloud.com
  resources:
  - useraccounts/status
  verbs:
  - get
